# Generated by Django 5.1.7 on 2026-05-10 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_invitation_id_alter_joinrequest_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojireaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='RoomActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('message', 'Message'), ('join', 'Join'), ('leave', 'Leave'), ('admin_transfer', 'Admin Transfer'), ('member_remove', 'Member Remove'), ('room_create', 'Room Create'), ('room_delete', 'Room Delete'), ('invitation_sent', 'Invitation Sent'), ('invitation_accept', 'Invitation Accept'), ('invitation_decline', 'Invitation Decline'), ('join_request', 'Join Request'), ('join_approve', 'Join Approve'), ('join_reject', 'Join Reject')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='chat.room')),
                ('target_user', models.ForeignKey(blank=True, help_text='User who is the target of this activity (e.g., removed member, new admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='chat_roomac_room_id_d26d66_idx'), models.Index(fields=['activity_type', '-created_at'], name='chat_roomac_activit_d4dd42_idx')],
            },
        ),
    ]
